trigger:
    - main


variables:
    serviceConnection: HDFC-Manual   
    vmImage: 'ubuntu-latest'
    backendServiceArm: '$(serviceConnection)'
    backendAzureRmResourceGroupName: 'backendRg'
    backendAzureRmStorageAccountName: 'javastorage2002'
    backendAzureRmContainerName: 'javac2002'
    backendAzureRmKey: 'java.terraform.tfstate'

stages:
  - stage: Terraform
    displayName: Terraform Infra

    jobs:
      - job: TerraformInfraCreation

        pool:
          vmImage: $(vmImage)
        
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: 'backendRg'
              backendAzureRmStorageAccountName: 'javastorage2002'
              backendAzureRmContainerName: 'javac2002'
              backendAzureRmKey: 'java.terraform.tfstate'
            
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: '-auto-approve'
              
   


          