trigger:
    - main


variables:
    serviceConnection: "HDFC-Manual"
    name: vmImage
    value: "ubuntu-latest"

stages:
  - stage: Terraform
    displayName: Terraform Infra

    jobs:
      - job: TerraformInfraCreation

        pool:
          vmImage: ${name} 
        
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'HDFC-Manual'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'HDFC-Manual'

